name: Lint

on:
  pull_request:
    branches:
      - "*"

jobs:
  initialize:
    name: initialize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
  lint:
    needs: initialize
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Run lint
        run: npm run lint
