name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: npm run lint
