name: validate

on:
  pull_request:
    branches:
      - "*"

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
