name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Publish
        run: pnpm publish:ga
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
