name: publish

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm-version: [7.27.0]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Publish
        run: pnpm publish
